name: ADR
description: Record a design decision
title: '[ADR]: description'
body:
  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: Have you searched for similar issues?
          required: true
  - type: dropdown
    id: platforms
    attributes:
      label: Platforms
      multiple: true
      options:
        - all
        - Website
        - Docs
        - Portal
      default: 0
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: A brief description of the what the issue of the design decision is
    validations:
      required: true
  - type: textarea
    id: decision
    attributes:
      label: Decision
      description: A brief description of the architectural decision taken
    validations:
      required: true
  - type: textarea
    id: comparative_table
    attributes:
      label: Comparative Table of Technologies
      description: |-
        Create a table comparing the different technologies that were considered and show pros and cons for specific use cases:

        ```
        | Use Case | Tech 1 | Tech 2 |
        |----------|--------|--------|
        | Use Case 1 |        |        |
        | Use Case 2 |        |        |
        | Use Case 3 |        |        |
        ```
  - type: textarea
    id: consequences
    attributes:
      label: Consequences and Results
      description: A description of the consequences and results of the decision
      placeholder: |-
        What are the consequences of the decision?
        Are there any other alternatives that were considered?
    validations:
      required: true
