  - type: textarea
    id: comparative_table
    attributes:
      label: Comparative Table of Technologies
      description: |-
        ### Comparative Table of Technologies
        | Use Case | Tech 1 | Tech 2 |
        |----------|--------|--------|
        | Use Case 1 |        |        |
        | Use Case 2 |        |        |
        | Use Case 3 |        |        |
      placeholder: |-
        ### Comparative Table of Technologies
        | Use Case | Tech 1 | Tech 2 |
        |----------|--------|--------|
        | Use Case 1 |        |        |
        | Use Case 2 |        |        |
        | Use Case 3 |        |        |
    validations:
      required: true
