blank_issues_enabled: true
contact_links:
  - name: FAQ
    url: https://brave.com/faq/
    about: Frequently Asked Questions
  - name: Help Center
    url: https://support.brave.com/
    about: Help Center
  - name: Community
    url: https://community.brave.com/
    about: Community support, this is the place to ask questions
issue_template:
  - name: Desktop issue
    about: "An issue affecting Linux, macOS, or Windows"
    labels: ["desktop"]
    title: "[Desktop Issue] "
  - name: Feature request
    about: "Request a new feature"
    labels: ["enhancement"]
    title: "[Feature] "
  - name: Bug
    about: "Report a bug"
    labels: ["bug"]
    title: "[Bug] "
